name: Deploy to Aws

# Trigger the workflow from the github ui
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
        - name: "Setup Nodejs"
          uses: actions/setup-node@v4
          with:
            node-version: 21
        - name: "Checkout"
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: "Install dependencies"
          run: npm install

        - name: "Run the test"
          run: npm test
        
        - name : "Deploy to Aws"
          run: pm2 start src/index.js